### ISSUE TITLE
Current user shouldn't be able to remove themselves or lower role

### ISSUE THREAD

**Issue by danielbachhuber** [Automattic/bulk-user-management#4]
The current user (e.g. the one performing the action) shouldn't be able to remove themselves or lower their role on the current site, as a user will most likely do so.

**Comment by joshbetz** [comment]
Already can't change role to something which wouldn't allow them to promote users. In order to prevent them for lower their role, I need to figure out a way to compare roles.

I can create a comparison method that compares capabilities. If one role doesn't have a capability that another does, it should be lower.

**Comment by danielbachhuber** [comment]
If they already can't remove their promote users cap, then it's probably not worth it writing logic to prevent themselves from changing roles (they can just change themselves back).

**Comment by joshbetz** [comment]
Perfect. That's what I was getting at.
